spring:
  application:
    name: smart-intervention-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,info"