spring:
  application:
    name: smart-intervention-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

security:
  jwt:
    secret: ${JWT_SECRET:J7qqEwYDpp8tEX6gg5zt8BaHtQWN6tAUK0oEvSUVOb0=}
    issuer: smart-intervention-platform
    expiration: PT1H

dashboard:
  analytics:
    refresh-interval: 300000 # 5 minutes in milliseconds
